In [43]:
import numpy as np

In [44]:
IDR2=[2458098, 2458099, 2458101, 2458102, 2458103, 2458104, 2458105, 2458106, \
2458107, 2458108, 2458109, 2458110, 2458111, 2458112, 2458113, 2458114, 2458115, \
2458116, 2458140]

In [45]:
bad_ants = np.empty((2, 19), list)
bad_ants[0,:] = IDR2
a = np.asarray([
[0,136,50,2],
[0,50],
[0,50],
[0,50,98],
[0,136,50,98],
[50,2],
[0,136,50,98],
[0,136,50],
[0,136,50,98],
[0,136,50],
[137,50,2],
[0,136,50],
[0,136,50],
[0,50],
[0,136,50,98],
[0,136,50,11],
[0,136,50],
[0,50,98],
[104,50,68,117]
])
# bad_ants[1,:] = a

In [46]:
a = np.array([np.array(xi) for xi in a])

In [47]:
bad_ants[1,:] = a

In [48]:
bad_ants

array([[2458098, 2458099, 2458101, 2458102, 2458103, 2458104, 2458105,
        2458106, 2458107, 2458108, 2458109, 2458110, 2458111, 2458112,
        2458113, 2458114, 2458115, 2458116, 2458140],
       [array([  0, 136,  50,   2]), array([ 0, 50]), array([ 0, 50]),
        array([ 0, 50, 98]), array([  0, 136,  50,  98]),
        array([50,  2]), array([  0, 136,  50,  98]),
        array([  0, 136,  50]), array([  0, 136,  50,  98]),
        array([  0, 136,  50]), array([137,  50,   2]),
        array([  0, 136,  50]), array([  0, 136,  50]), array([ 0, 50]),
        array([  0, 136,  50,  98]), array([  0, 136,  50,  11]),
        array([  0, 136,  50]), array([ 0, 50, 98]),
        array([104,  50,  68, 117])]], dtype=object)

In [49]:
bad_ants_casa = np.copy(bad_ants)

In [54]:
bad_ants_casa[1, :] += 1

In [55]:
bad_ants_casa

array([[2458098, 2458099, 2458101, 2458102, 2458103, 2458104, 2458105,
        2458106, 2458107, 2458108, 2458109, 2458110, 2458111, 2458112,
        2458113, 2458114, 2458115, 2458116, 2458140],
       [array([  1, 137,  51,   3]), array([ 1, 51]), array([ 1, 51]),
        array([ 1, 51, 99]), array([  1, 137,  51,  99]),
        array([51,  3]), array([  1, 137,  51,  99]),
        array([  1, 137,  51]), array([  1, 137,  51,  99]),
        array([  1, 137,  51]), array([138,  51,   3]),
        array([  1, 137,  51]), array([  1, 137,  51]), array([ 1, 51]),
        array([  1, 137,  51,  99]), array([  1, 137,  51,  12]),
        array([  1, 137,  51]), array([ 1, 51, 99]),
        array([105,  51,  69, 118])]], dtype=object)

In [38]:
bad_ants_casa = bad_ants
# Converting ant number from HERA to CASA (adding 1)
for i in range(len(bad_ants[1,:])):
    for j in range(len(bad_ants[1,i])):
        bad_ants_casa[1, i][j] = bad_ants[1, i][j] + 1

In [18]:
bad_ants[1, :]

array([list([1, 137, 51, 3]), list([1, 51]), list([1, 51]),
       list([1, 51, 99]), list([1, 137, 51, 99]), list([51, 3]),
       list([1, 137, 51, 99]), list([1, 137, 51]), list([1, 137, 51, 99]),
       list([1, 137, 51]), list([138, 51, 3]), list([1, 137, 51]),
       list([1, 137, 51]), list([1, 51]), list([1, 137, 51, 99]),
       list([1, 137, 51, 12]), list([1, 137, 51]), list([1, 51, 99]),
       list([105, 51, 69, 118])], dtype=object)

In [15]:
bad_ants_casa

array([[2458098, 2458099, 2458101, 2458102, 2458103, 2458104, 2458105,
        2458106, 2458107, 2458108, 2458109, 2458110, 2458111, 2458112,
        2458113, 2458114, 2458115, 2458116, 2458140],
       [list([1, 137, 51, 3]), list([1, 51]), list([1, 51]),
        list([1, 51, 99]), list([1, 137, 51, 99]), list([51, 3]),
        list([1, 137, 51, 99]), list([1, 137, 51]),
        list([1, 137, 51, 99]), list([1, 137, 51]), list([138, 51, 3]),
        list([1, 137, 51]), list([1, 137, 51]), list([1, 51]),
        list([1, 137, 51, 99]), list([1, 137, 51, 12]),
        list([1, 137, 51]), list([1, 51, 99]), list([105, 51, 69, 118])]],
      dtype=object)